### PR TITLE
Update Documentation for ConstantTags

### PR DESCRIPTION
**Pull request by lemkepf**
Quick syntax fix to documentation. Incorrect c# syntax was listed... my OCD was making me tick.

### CODE REVIEW

**Comment by gzussa** [comment]
Thanks a lot for this fix 👍

**Comment by apigirl** [comment]
hey @lemkepf - would love to get this merged in. Could you please fix the merge conflict, or give me access to your fork so that I can?

**Comment by apigirl** [comment]
merge conflict fixed in #95

**Comment by irabinovitch** [comment]
Closing in favor for #95. @lemkepf, we'll make sure to thank you in the release notes PR.  Thanks for your contribution here!

**Comment by irabinovitch** [comment]
Closing in favor for #95. @lemkepf, we'll make sure to thank you in the release notes PR.  Thanks for your contribution here!

**Pull request merged**
