### PR TITLE
Abstractions

### PR DESCRIPTION
**Pull request by nrjohnstone**
We are using DataDog and the lack of an abstraction over the static DogStatsd is an impedance in our TDD and test coverage.

Refactoring to provide an interface IDogStatsd and an instance based DogStatsdService for those people using TDD. 

Also still provides the ability to register the instance with your IoC container as a singleton if we want to retain the current "static" functionality

### CODE REVIEW

**Comment by nrjohnstone** [comment]
Can this be reviewed at some point? It would be nice to be able to plan on retiring our internal abstractions and just rely on the DataDog nuget package providing them

**Comment by yannmh** [comment]
Hello @nrjohnstone,

Thanks a lot for your contribution. I apologize for the delay in responding to you.
We are planning a new release for the end of next week: I'll take a pass at it by that date, so it can go out with it 🚢  :)

**Comment by nrjohnstone** [comment]
@yannmh are you able to give an eta of when 2.2.0 will be cut? We are in need of the "check" API methods that have been added to enable better reporting of the internal application state and I don't want to have to build our own internal version if you guys are releasing soon

**Comment by yannmh** [comment]
@nrjohnstone Yes, we are planning a new release Friday, later Monday, August 1st.

**Comment by nrjohnstone** [comment]
@yannmh any update on getting this merged and when 2.2.0 is coming?

**Comment by nrjohnstone** [comment]
@yannmh can I get an update on the release date for 2.2.0

**Comment by nrjohnstone** [comment]
wtf? I opened this on August .. we have been using our own abstractions internally while waiting for this to get merged and release... are you going to use it or not ?

**Comment by yannmh** [comment]
I  apologize for the delay on this @nrjohnstone !

The [transition to .NET Core](https://github.com/DataDog/dogstatsd-csharp-client/pull/30) took most of our time, and lead us to drop the initial relae roadmap. I moved the card back in `Triage` two weeks ago, while I was drawing out a new roadmap and release plan. 

We are planning a new major release today, and this will be included. I  have rebased your changed and opened a new PR: #40 .  You will be credited in the changelog and release notes.

**Pull request closed without merging**
