### PR TITLE
[project] port to .NET Core

### PR DESCRIPTION
**Pull request by yannmh**
Original discussion thread: #28
Credits to @wjdavis5  (https://github.com/wjdavis5 ) . Thanks a lot !!! 🙇 

### New repository structure

* Remove the deprecated `StatsdClient.Configuration` class
* Reorganize the project to support and compile on .NET Framework and .NET Core side-by-side.

References:
* https://docs.microsoft.com/en-us/dotnet/articles/core/porting/project-structure
* https://github.com/dotnet/core-docs/tree/master/samples/framework/libraries

### Supported platforms

* .NET Framework 4.5.1 
* .NET Standard 1.3

### Build and testing

Setup AppVeyor to
* Build on all supported frameworks
* Test on .NET Framework 4.5.1 and 4.6

Instructions to run the tests are described in the README.

### CODE REVIEW

**Comment by wjdavis5** [comment]
A couple of comments:

1. Is there any particular reason to maintain .NET 3.5 support?
2. You may consider using Net Standard 1.3 instead of 1.6

Regarding 1:
I'm not sure if you have any metrics related to which .net platforms are utilizing the existing code base, however the contemporary direction is to work really hard to get to .NET 4.6 so as to better support the entire NetCore / Standard APIs. Maintaining support for 3.5 long term is going to become more of a PIA as the NetStandard API matures. Given this release would probably constitute a major version increment, you may consider dropping support moving forward for 3.5. 

Regarding 2:
Admittedly I still struggle grasping the semantics and naming regarding this whole .NET Core / Standard thing. That being said I've been closely following the Apache Log4Net project which is also currently preparing to release .NET Core support. They have opted to go with Net Standard 1.3
[here](https://github.com/apache/log4net/pull/16)
You can see the compatability flow [here](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) 
Search "What’s new in .NET Standard 2.0?"

@chlowell specifically says:

> Targeting netstandard1.6 here is more limiting than useful. Doing so would remove support for current UWP apps, and the larger API surface won't light up any major features.

Ping me if you need any direction working with Appveyor, and thanks for moving this along!

**Comment by yannmh** [comment]
> Is there any particular reason to maintain .NET 3.5 support?

My first thought was to do it, if we can and it's easy to. However I realize it tends to make the library design and the workflow a little cumbersome, i.e. 
* More preprocessor symbols to play well with the various platforms 
* Two test runners have to run: `nunit-console` (for `net35`) which is not compatible with .NET Core and `dotnet-test-nunit` for .NET Core.

Thus, on second thought, I agree with you and believe we should drop the .NET Framework 3.5 compatibility. I don't have any metrics about the .NET platform usage, but if necessary, the [2.x branch](https://github.com/DataDog/dogstatsd-csharp-client/tree/2.x) can be used to port a BUGFIX and release it for older platforms.
This backward compatibility change would also be made clear: it follows a major version increment and a highlight in the CHANGELOG.  

> You may consider using Net Standard 1.3 instead of 1.6

I switched to `netstandard1.3` which is the lowest version we can support without additional code changes.



Again, thanks a lot for your help @wjdavis5 🙇 

@truthbk can you take a pass

**Comment by wjdavis5** [comment]
You may notice that the nuget package that is built with `dotnet pack` uses the version information in the project.json file.
I have created a repo with a node script that updates this information with the current Appveyor build number

https://github.com/wjdavis5/NetCoreProjectVersionIncrement

The pre build script is:

```
npm install jsonfile
node version.js
dotnet restore
```

**Comment by wjdavis5** [comment]
Also it looks like the statsd client is getting some traction on porting as well:
https://github.com/Pereingo/statsd-csharp-client/pull/56

**Comment by yannmh** [comment]
Let's merge this and release 🎉 . 
<br>

> You may notice that the nuget package that is built with dotnet pack uses the version information in the project.json file.
I have created a repo with a node script that updates this information with the current Appveyor build number

That sounds good 🙇 . Once this is out, I'll take a second pass at making the CI better.

**Pull request merged**
